### ISSUE TITLE
Invalid handler results in no error

### ISSUE THREAD

**Issue by eproxus** [max-au/argparse#3]
When setting a specific handler on the top level:

```
main(Args) -> cli:run(Args).

cli() -> #{handler => {?MODULE, foobar}}.

cli(_Args) -> ok.
```

It is ignored and instead the program returns successfully.

**Comment by max-au** [comment]
Accidentally mentioned a different PR for this issue.
So this handler is perfectly valid!
It means that ?MODULE:foobar is a function that accepts parsed argument map:

    foobar(#{left := Left, right := Right}) ->
       Left * Right.

Looking more into this very specific example.
cli mini-framework merges only 'arguments' and 'commands' from the map returned by cli/0 callback. So, handler definition is indeed ignored, and cli mini-framework calls cli/1 (that simply returns 'ok').

It seems possible to honour 'handler', and run it instead of cli/1. Only issue could be when multiple modules return different 'handler', in that case, first one to find will be run.

**Comment by eproxus** [comment]
The same warnings as for global `arguments` key could be used perhaps, when multiple handlers are defined?

**Comment by max-au** [comment]
Yes, this makes total sense. It can also let me get rid of optional cli/1 callback (that hopefully isn't used by anyone yet).

**Comment by max-au** [comment]
Implemented in https://github.com/max-au/argparse/pull/7
