### ISSUE TITLE
Documentation generation using rebar3_ex_doc?

### ISSUE THREAD

**Issue by kianmeng** [max-au/argparse#42]
Hey @max-au, 
Is there a plan to switch the documentation generation to https://github.com/starbelly/rebar3_ex_doc?

**Comment by max-au** [comment]
Yes, absolutely. I have a patch pending (similar to https://github.com/max-au/erlperf/commit/45852d9a25da558af7fc8de5a688a8064ed09893).

**Comment by max-au** [comment]
I ran into an issue trying to ex_doc-ify argparse and erlperf. This one: https://github.com/starbelly/rebar3_ex_doc/issues/26 

ex_doc simply deletes the entire "doc" folder (that contains examples and actual documentation). It could be worked around by renaming the directory, but then it would not be standard OTP naming. Will see when the problem is resolved and re-attempt.

**Comment by kianmeng** [comment]
> ex_doc simply deletes the entire "doc" folder (that contains examples and actual documentation).

I see. Similar to the issue raised here, https://github.com/starbelly/rebar3_ex_doc/issues/19#issuecomment-1126797133 which will require changes in `ex_doct` itself.

> It could be worked around by renaming the directory, but then it would not be standard OTP naming.

I assumed the "standard OTP naming" was following this guide here, https://www.erlang.org/doc/design_principles/applications.html#directory-structure-guidelines-for-a-development-environment?

**Comment by max-au** [comment]
Yes, that's exactly the problem. Ideally I'd prefer `ex_doc` output to go to the build folder, as source folders may be read-only.

And yes, I'd prefer to follow OTP naming recommendations you linked.

**Comment by max-au** [comment]
Now that issues with rebar3_ex_doc are fixed (mainly in ExDoc itself), this had been finally completed.
